services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"

  backend:
    image: kaushik62/investo:backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/Investo
      - JWT_SECRET=your_jwt_secret_here
      - PORT=5000
    depends_on:
      - mongodb

  frontend:
    image: kaushik62/investo:frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend